name: app
description: "SOCIAL HUB."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_web_plugins:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  hive: ^2.2.3
  injectable: ^2.6.0
  json_annotation: ^4.9.0
  theme_tailor: ^3.1.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
